### ISSUE TITLE
Typescript as supported language for schema output

### ISSUE THREAD

**Issue by urianawu** [grafana/grok#37]
Our team uses Grafana Cloud as our main monitoring platform and is looking to scale by investing in IaC. While Grafonnet(jsonnet) is the official IaC library, I was wondering whether the team would consider supporting Typescript? 

Reasons for why Typescript support can help:
- Most of the developers developing in our code base's expertise is in front-end. Typescript support will make it easier for developers to provision dashboards via code.
- I have found a couple open API schema to TS converters ([openapi-typescript](https://github.com/drwpow/openapi-typescript)  etc.) so it potentially is self-service to generate the TS types. However maintaining the TS types would be the issue as re-generating is required with any schema update in Grafana.

**Comment by K-Phoen** [comment]
Hey!

Generating Typescript output is something we're indeed interested in :)

It won't be done using grok though, as we decided to abandon this experiment.

Instead of grok, we're using [cog](https://github.com/grafana/cog/) to generate both types and *builder libraries* in a range of languages, including Typescript. You can find a preview of these generated outputs in [grafana-foundation-sdk](https://github.com/grafana/grafana-foundation-sdk/tree/v10.2.x%2Bcog-v0.0.x)

**Comment by urianawu** [comment]
This is awesome news! Upon a quick scan the new sdk has everything we need, I will definitely try them out.
